# Generated by Django 3.1.3 on 2020-11-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detailPerson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('certification', models.CharField(max_length=100)),
                ('detailperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detailPerson.detailperson')),
            ],
        ),
    ]
