# Generated by Django 3.1.3 on 2020-11-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('myProject', '0001_initial'),
        ('detailCV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_cv',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.education'),
        ),
        migrations.AddField(
            model_name='detail_cv',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myProject.project'),
        ),
    ]
