# Generated by Django 3.1.3 on 2020-11-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUni', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('CPA', models.FloatField(default=0)),
                ('time_at_started', models.DateTimeField()),
                ('time_at_finished', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.university')),
            ],
        ),
    ]
